### ISSUE TITLE
Font-size inconsistency on About page

### ISSUE THREAD

**Issue by geealbers** [gettypubs/ancientlamps#76]
In the small text section of the About page, `ul` text is rendering larger than `p` text. In the screenshot, the highlighted line is a `p` whereas the text surrounding it is lists. The image credits at the bottom are also in a paragraph.

<img width="1050" alt="screen shot 2017-06-30 at 1 28 09 pm" src="https://user-images.githubusercontent.com/7796401/27752903-284d16b8-5d98-11e7-8a72-a61312336f04.png">

The relevant css, I think, is in `_global.scss`:

```css
.smaller-text {
  h2 { font-size: modular-scale(2); }
  h3 { font-size: modular-scale(1); }
  h4 { font-size: modular-scale(1); }
  p { font-size: modular-scale(0); margin-bottom: 1rem; }
  ul li { font-size: modular-scale(-1); }
  blockquote {font-size: modular-scale(0); text-indent: 0;}

  p + p { text-indent: 0; }

  ul {
    list-style-type: none;
    padding: 0;
    margin-bottom: 1rem;
  }
}
```
